language: elixir

sudo: false

otp_release: '22.0'
elixir: '1.9'

stages:
  - check formatted
  - test

jobs:
  include:
    - stage: test

    - otp_release: '18.3'
      elixir: '1.3'

    - stage: check formatted
      script: mix format --check-formatted
