language: elixir

sudo: false

otp_release: '21.1'
elixir: '1.7'

stages:
  - check formatted
  - test

jobs:
  include:
    - stage: test

    - otp_release: '18.3'
      elixir: '1.3'

    - stage: check formatted
      script: mix test --check-formatted
